### ISSUE TITLE
Can This Be used In an Asp.net Core application

### ISSUE THREAD

**Issue by nafberger** [jsgoupil/quickbooks-sync#24]

**Comment by jsgoupil** [comment]
@adamskt Hey, someone is asking about .net core and I remember you did some work on this. I am ready to try upgrading the WebConnector to .netcore2.0 but I am wondering why that one didn't get converted to support multiple frameworks?

**Comment by adamskt** [comment]
I am currently using this library in a netstandard2.0 project which is consumed by a v2 Azure Function (which uses the netcoreapp2.0 runtime, AFAIK).  I also consume the same library in a netcoreapp2.0 console application.  If I remember correctly, WebConnector didn't get upgraded to netstandard2.0 because it depends on Nito.AsyncEx v4.0.1 which has it's highest targeted TFM as net451.  There is a pre-release of Nito.AsyncEx 5 that targets newer frameworks, but I remember some changes to it's API that made upgrading WebConnector non-trivial.

**Comment by jsgoupil** [comment]
Thanks for your answer!
But aren't you consuming only qbxml ?
This Nito, I recall using it but it's a tiny library that could be removed I think. But I just checked and they seem to support .netcoreapp1.3

**Comment by adamskt** [comment]
That's right, I'm only using the qbxml portion of the library, if I recall correctly.  I agree with you on the possibility of removing Nito-- I think the need for it is largely made redundant by the richness of the TPL in newer frameworks.

**Comment by nafberger** [comment]
Hi, can I contact either of you above, we are ready to pay for technical help to get this to work for us. feel free to contact me on 845-421-5042 or nafberger@gmail.com

**Comment by jsgoupil** [comment]
Let me give you a call to check what you need.

**Comment by jsgoupil** [comment]
Done!
